#!/bin/csh

#supply number of iterations, seed, starting structure
# remaining arguments are ATTRACT arguments
#  (structures.dat and --traj are added automatically)
# result is in montevideo-traj.dat and montevideo-top.dat

set args = `echo $* | awk '{for(n = 4; n <= NF; n++) code = code $n " "} END{print code}'`

set seed = $2

set traj = `mktemp`
set top = `mktemp`
set alltop = `mktemp`
set temp = `mktemp`
set temp2 = `mktemp`

cat /dev/null > $traj
cat $3 > $top
foreach i (`awk -v c=$1 'BEGIN{for (i=1;i<=c;i++) print i}'`)
  echo $i
  echo TOP
  cat $top
  echo
  if ($i > 1) then
    python $0:h/../tools/monte.py $top --fix-receptor --seed $seed > $temp
    set seed = `expr $seed + 1`    
  else
    cat $top > $temp
  endif
  #echo START
  #cat $temp
  #echo
  $0:h/../bin/attract $temp $args --traj > $temp2
  $0:h/../tools/add $traj $temp2 > $temp
  cat $temp > $traj
  $0:h/../tools/last $temp2 > $temp
  echo LAST
  cat $temp
  echo
  if ($i > 1) then
    python $0:h/../tools/metro.py $top $temp > $temp2  
    cat $temp2 > $top
  else
    cat $temp > $top
  endif
  $0:h/../tools/add $alltop $top > $temp
  cat $temp > $alltop
end
cat $traj > montevideo-traj.out
cat $alltop > montevideo-top.out
rm -f $traj $top $temp $temp2 $alltop


