#!/usr/bin/python

"""
Minimalistic ATTRACT interface file editor

To edit an existing ATTRACT interface file, supply it on the command line:
  attract-editor attract.web
To create a new one, don't supply a second argument:
  attract-editor

The "Save" button saves the edited file (to the same file, or to new.web
 if no file was supplied)

The "Generate shell script" button generates an executable protocol


Any exceptions will be printed on screen

"""

from __future__ import print_function

import sys, os

argv = [a for a in sys.argv if not a.startswith("--")]
if len(argv) == 1:
  inp = None
  outp = "new.web"
elif len(argv) == 2:
  inp = argv[1]
  d,f = os.path.split(inp)
  if len(d): os.chdir(d)
  inp = f  
  outp = inp
else: 
 raise Exception("Usage: attract-editor [file name]")

try:
  import spyder
  from gi.repository import Gtk
except ImportError:
  import traceback
  traceback.print_exc()
  if sys.platform == "win32":
    time.sleep(30) 
  sys.exit()    
from spyder.gtkform import gtkview
import attractmodel
from Spyder import AttractModel

from spyder.formtools import model, controller

spydertype = AttractModel

form = spydertype._form()
form.add_button("Generate shell script", "after")
form.add_button("Save", "after")


#construct model, controller, comparator
m = model(spydertype._typetree())  #or: m = model(spydertype)
con = controller(form, m)

#optional: initialize model 
if inp is not None:
  params = AttractModel.fromfile(inp)
  m._set(params)
  
#build view
xml = spyder.gtkform.xml(spydertype, form=form)
builder = Gtk.Builder()
builder.add_from_string(xml)
v = gtkview.gtkview(form)
v._wrap(builder)

#bind view to controller
con._bind_view(v)
#listen for model updates
con._listen()
#synchronize
con._sync_to_view()
con._sync_from_view() 

#register view listener 
# (note the order, after the mvc binding! The viewupdate will now be invoked last)

####################################################################

old_status = None
def viewupdate(*args):  
  global old_status
  status = m._status(con)
  if status == old_status: return
  print(status)
  old_status = status
  
####################################################################    

import attractsave
from functools import partial

v.buttons[0].listen(partial(attractsave.save, m, outp))
v.buttons[1].listen(partial(attractsave.generate, m, outp))
v.listen(viewupdate)

#fire up application
window = builder.get_object("window1") 
window.connect("delete-event", Gtk.main_quit)
window.show_all()
Gtk.main()
