#!/bin/sh
silk --default-output attract.web AttractModel -m attractmodel -I $ATTRACTGUI --gui html \
 -I $ATTRACTGUI/server --form form_model webform --view form_model html --webdir $ATTRACTGUI/server/html --webserver-pre form_model webserverform $@
