#!/bin/sh
silk --default-output attract.web CryoInterface -I $ATTRACTGUI -m attractmodel --gui html \
-I $ATTRACTGUI/server --form form_cryo webform --view form_cryo html --webdir $ATTRACTGUI/server/html --webserver-pre form_cryo webserverform $@