#!/bin/sh
silk --default-output attract.web CryoEasyInterface -I $ATTRACTGUI -m attractmodel --gui html \
-I $ATTRACTGUI/server --form form_cryo_easy webform --view form_cryo_easy html --webdir $ATTRACTGUI/server/html --webserver-pre form_cryo_easy webserverform $@
