#!/usr/bin/python
import sys
from _read_struc import read_struc
import random
from math import *
header,structures = read_struc(sys.argv[1])
header2,structures2 = read_struc(sys.argv[2])
if len(header) == 0: header = header2
if len(header2) == 0: header2 = header
if header != header2: raise Exception("Headers are not the same")

print "## add.py:"
for h in header: print h
stnr = 0
for s in structures + structures2:
  stnr += 1
  l1,l2 = s
  print "#"+str(stnr)
  for l in l1: print l
  for l in l2: print l
