#!/usr/bin/env python2
import sys
files = [open(f) for f in sys.argv[1:]]

for lines in zip(*files):
  linefields = [l.split() for l in lines]
  data = []
  for l in linefields: 
    assert len(l) == 1
    data.append(float(l[0]))  
  print max(data)
    
  
  