#!/usr/bin/python

import sys
f = sys.argv[1]
assert f.endswith(".pdb")

header = []
count = 0
for l in open(f):
  l = l.rstrip("\n")
  if l.startswith("MODEL"): 
    if count > 0: ff.close()
    count += 1
    ff = open(f[:-4]+"-"+str(count)+".pdb", "w")
    for h in header: print >> ff, h
    continue
  if l.startswith("ENDMDL"): continue
  if count == 0: header.append(l)
  else: print >> ff, l
