#!/usr/bin/python

import sys
f = sys.argv[1]
assert f.endswith(".pdb")

count = 0
init = True
for l in open(f):
  l = l.rstrip("\n")
  if l.startswith("ATOM") and init: 
    if count > 0: ff.close()
    count += 1
    ff = open(f[:-4]+"-"+str(count)+".pdb", "w")
    init = False
  if l.split()[0] == "END": 
    init = True
    continue
  if not init: print >> ff, l
